---
scenario:
  name: default
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: stretch64
    box: debian/stretch64
    memory: 512
    cpus: 1
  - name: centos7
    box: centos/7
    memory: 512
    cpus: 1
provisioner:
  name: ansible
  become: true
  lint:
    name: ansible-lint
    enabled: False
  playbooks:
    converge: playbook.yml
lint:
  name: yamllint
  enabled: True
verifier:
  name: goss
  lint:
    name: yamllint
